Переписала конфиг в yml-файл, добавила тесты для кнопки типа «bright»…
redveronika/ya-mm-task pull request #177
Opened 2017-11-19 13:10 UTC by redveronika

…, добавила скриншоты в репозиторий
close #176

2017-11-19 16:56 UTC, sbmaxx requested changes

2017-11-19 16:56 UTC, sbmaxx commented on app/tests/gemini/button.js
> +    gemini.suite('bright button', (brightButton) => {
по идее, можно через цикл организовать эти два теста

2017-11-19 19:08 UTC, sbmaxx commented on app/tests/gemini/button.js
> +                .setCaptureElements(button)
в имени файлов можно бы и без точки

2017-11-19 19:48 UTC, redveronika commented
@sbmaxx 😉

2017-11-19 21:13 UTC, sbmaxx commented on app/tests/gemini/button.js
> +        gemini.suite(`${button.replace(/[.-]+/g, ' ').trim()} capturing`, (element) => {
пробелы в имени файлов ну тоже так себе идея ;)

2017-11-20 08:57 UTC, redveronika commented
@sbmaxx Рома, приди!

2017-11-20 11:49 UTC, sbmaxx approved these changes

2017-11-20 12:09 UTC, merged